remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: https://github.com/nubiscursor/nubiscursor.github.io.git
title: Cloud Runner
description: A simple way to document I.T projects
